import type { TDocumentDefinitions, Content } from 'pdfmake/interfaces'
import { formatAmount } from '@/shared/lib/amount-utils'
import { getNetworkName } from '@/entities/network'
import { APP_URLS } from '@/shared/config'

import type { PartialInvoice } from '@/shared/lib/invoice-types'
import type { PdfExportOptions } from '../model/types'

import { COLORS, CONTENT_WIDTH } from './pdf-theme'
import { computeTotals, getDisplayTotal } from './pdf-calculations'
import { buildHeader } from './pdf-header'
import { buildParties } from './pdf-parties'
import { buildLineItems } from './pdf-line-items'
import { buildBottomSection, buildContentFooter } from './pdf-bottom'

// ── Separators ──────────────────────────────────────────────

/** Thick dark rule matching web border-b-2 border-zinc-700 */
function thickRule(): Content {
  return {
    canvas: [{ type: 'line', x1: 0, y1: 0, x2: CONTENT_WIDTH, y2: 0, lineWidth: 1.5, lineColor: COLORS.borderThick }],
    margin: [0, 12, 0, 12],
  }
}

/** Dashed rule matching web border-t border-dashed border-zinc-300 */
function dashedRule(): Content {
  return {
    canvas: [{
      type: 'line', x1: 0, y1: 0, x2: CONTENT_WIDTH, y2: 0,
      lineWidth: 0.5, lineColor: COLORS.borderDashed,
      dash: { length: 4, space: 3 },
    }],
    margin: [0, 10, 0, 10],
  }
}

// ── Public API ──────────────────────────────────────────────

/**
 * Build pdfmake document definition from invoice data.
 * Layout closely matches the web InvoicePaper component.
 */
export function buildDocument(
  data: PartialInvoice,
  options: PdfExportOptions
): TDocumentDefinitions {
  const decimals = data.decimals ?? 6
  const currency = data.currency ?? ''
  const invoiceId = data.invoiceId ?? 'DRAFT'
  const networkName = data.networkId ? getNetworkName(data.networkId) : ''
  const totals = computeTotals(data, decimals)

  return {
    pageSize: 'A4',
    pageOrientation: 'portrait',
    pageMargins: [50, 50, 50, 60] as [number, number, number, number],
    watermark: options.status && options.status !== 'pending'
      ? { text: options.status.toUpperCase(), opacity: 0.10, bold: true, fontSize: 72, color: COLORS.muted }
      : undefined,
    content: [
      buildHeader(invoiceId, data, options),
      thickRule(),
      buildParties(data),
      buildLineItems(data.items, decimals),
      thickRule(),
      buildBottomSection(totals, currency, data, networkName, options),
      dashedRule(),
      buildContentFooter(data.notes),
    ],
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: COLORS.text,
      lineHeight: 1.3,
    },
    footer: {
      text: [
        { text: 'Generated by VoidPay \u00B7 ', color: COLORS.muted },
        { text: 'voidpay.xyz', color: COLORS.muted, link: APP_URLS.base },
      ],
      alignment: 'center',
      fontSize: 7.5,
      margin: [0, 15, 0, 0],
    },
  }
}

/** Strip unsafe characters from filename parts */
function sanitizeFilenamePart(s: string): string {
  return s.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 50)
}

/**
 * Generate PDF filename from invoice data.
 * Format: voidpay-{invoiceId}-{total}-{currency}.pdf
 */
export function buildFilename(data: PartialInvoice): string {
  const id = data.invoiceId ? sanitizeFilenamePart(data.invoiceId) : undefined
  const currency = data.currency ? sanitizeFilenamePart(data.currency) : undefined
  const decimals = data.decimals ?? 6

  if (!id && !data.total) return 'voidpay-invoice.pdf'

  let totalStr: string | undefined
  try {
    const rawTotal = data.total ? getDisplayTotal(data.total, data.magicDust) : undefined
    totalStr = rawTotal
      ? formatAmount(rawTotal, decimals, { useGrouping: false })
      : undefined
  } catch {
    totalStr = undefined
  }

  const parts = ['voidpay']
  if (id) parts.push(id)
  if (totalStr) parts.push(totalStr)
  if (currency) parts.push(currency)

  return parts.length > 1 ? `${parts.join('-')}.pdf` : 'voidpay-invoice.pdf'
}
