import type { TDocumentDefinitions, Content, ContentColumns, Column } from 'pdfmake/interfaces'
import { formatAmount, calculateTotalsBigInt } from '@/shared/lib/amount-utils'
import { formatDateUTC } from '@/shared/lib/date-time'
import { getNetworkName } from '@/entities/network'

import type { PartialInvoice } from '@/shared/lib/invoice-types'
import type { PdfExportOptions } from '../model/types'

// ── Colors (matching web InvoicePaper zinc/violet palette) ──

const COLORS = {
  black: '#18181b',       // zinc-900
  text: '#27272a',        // zinc-800
  textMd: '#3f3f46',      // zinc-700 (rate, qty values)
  zinc600: '#52525b',     // zinc-600 (row index)
  muted: '#71717a',       // zinc-500
  light: '#a1a1aa',       // zinc-400
  placeholder: '#d4d4d8', // zinc-300
  borderThick: '#3f3f46', // zinc-700 (header / table thick borders)
  borderLight: '#e4e4e7', // zinc-200 (row borders, card borders)
  borderDashed: '#d4d4d8', // zinc-300 (footer dashed)
  brand: '#7c3aed',       // violet-600 (total amount)
  bgLight: '#fafafa',     // zinc-50 (card body, zebra rows)
  bgMuted: '#f4f4f5',     // zinc-100 (card header)
  taxRed: '#991b1b',      // red-800
  discountGreen: '#059669', // emerald-600
  txBg: '#ecfdf5',        // emerald-50
  txBorder: '#a7f3d0',    // emerald-200
  txText: '#065f46',      // emerald-800
} as const

/** Content width for A4 with 50pt margins: 595 - 50 - 50 */
const CONTENT_WIDTH = 495

// ── Public API ──────────────────────────────────────────────

/**
 * Build pdfmake document definition from invoice data.
 * Layout closely matches the web InvoicePaper component.
 */
export function buildDocument(
  data: PartialInvoice,
  options: PdfExportOptions
): TDocumentDefinitions {
  const decimals = data.decimals ?? 6
  const currency = data.currency ?? ''
  const invoiceId = data.invoiceId ?? 'DRAFT'
  const networkName = data.networkId ? getNetworkName(data.networkId) : ''
  const totals = computeTotals(data, decimals)

  return {
    pageSize: 'A4',
    pageOrientation: 'portrait',
    pageMargins: [50, 50, 50, 60] as [number, number, number, number],
    watermark: options.status
      ? { text: options.status.toUpperCase(), opacity: 0.10, bold: true, fontSize: 72, color: COLORS.muted }
      : undefined,
    content: [
      buildHeader(invoiceId, data, options),
      thickRule(),
      buildParties(data),
      buildLineItems(data.items, decimals),
      thickRule(),
      buildBottomSection(totals, currency, data, networkName, options),
      dashedRule(),
      buildContentFooter(data.notes),
    ],
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: COLORS.text,
      lineHeight: 1.3,
    },
    footer: {
      text: 'Generated by VoidPay \u00B7 voidpay.xyz',
      alignment: 'center',
      fontSize: 7.5,
      color: COLORS.muted,
      margin: [0, 15, 0, 0],
    },
  }
}

/**
 * Generate PDF filename from invoice data.
 * Format: voidpay-{invoiceId}-{total}-{currency}.pdf
 */
export function buildFilename(data: PartialInvoice): string {
  const id = data.invoiceId
  const currency = data.currency
  const decimals = data.decimals ?? 6

  if (!id && !data.total) return 'voidpay-invoice.pdf'

  const totalStr = data.total
    ? formatAmount(data.total, decimals, { useGrouping: false })
    : undefined

  const parts = ['voidpay']
  if (id) parts.push(id)
  if (totalStr) parts.push(totalStr)
  if (currency) parts.push(currency)

  return parts.length > 1 ? `${parts.join('-')}.pdf` : 'voidpay-invoice.pdf'
}

// ── Separators ──────────────────────────────────────────────

/** Thick dark rule matching web border-b-2 border-zinc-700 */
function thickRule(): Content {
  return {
    canvas: [{ type: 'line', x1: 0, y1: 0, x2: CONTENT_WIDTH, y2: 0, lineWidth: 1.5, lineColor: COLORS.borderThick }],
    margin: [0, 12, 0, 12],
  }
}

/** Dashed rule matching web border-t border-dashed border-zinc-300 */
function dashedRule(): Content {
  return {
    canvas: [{
      type: 'line', x1: 0, y1: 0, x2: CONTENT_WIDTH, y2: 0,
      lineWidth: 0.5, lineColor: COLORS.borderDashed,
      dash: { length: 4, space: 3 },
    }],
    margin: [0, 10, 0, 10],
  }
}

// ── Header (matches PaperHeader.tsx) ────────────────────────

function buildHeader(
  invoiceId: string,
  data: PartialInvoice,
  options: PdfExportOptions
): ContentColumns {
  const issuedDate = data.issuedAt ? formatDateUTC(data.issuedAt) : '\u2014'
  const dueDate = data.dueAt ? formatDateUTC(data.dueAt) : '\u2014'
  const isDraft = invoiceId === 'DRAFT'

  // Left: "INVOICE #ID" matching web text-4xl font-black uppercase
  const titleLine: Content = {
    text: [
      { text: 'INVOICE ', fontSize: 26, bold: true, color: COLORS.light },
      isDraft
        ? { text: 'Draft', fontSize: 26, italics: true, color: COLORS.placeholder }
        : { text: `#${invoiceId}`, fontSize: 26, bold: true, color: COLORS.black },
    ],
  }

  // Right: stacked date rows matching web vertical layout
  const metaRows: Content[] = [
    metaRow('ISSUED', issuedDate),
    metaRow('DUE', dueDate, [0, 4, 0, 0]),
  ]

  if (options.status) {
    metaRows.push(metaRow('STATUS', options.status.toUpperCase(), [0, 4, 0, 0], COLORS.brand))
  }

  return {
    columns: [
      { stack: [titleLine], width: '*' } as Column,
      { stack: metaRows, width: 170, alignment: 'right' } as Column,
    ],
  }
}

function metaRow(
  label: string,
  value: string,
  margin?: [number, number, number, number],
  valueColor?: string
): Content {
  return {
    columns: [
      { text: label, fontSize: 8, bold: true, color: COLORS.light, width: 48, characterSpacing: 1.2 },
      { text: value, fontSize: 10, bold: !!valueColor, color: valueColor ?? COLORS.text, alignment: 'right' as const },
    ],
    ...(margin ? { margin } : {}),
  }
}

// ── Parties (matches PartyInfo.tsx) ─────────────────────────

function buildParties(data: PartialInvoice): ContentColumns {
  return {
    columns: [
      partyColumn('FROM', data.from, 'left'),
      partyColumn('BILL TO', data.client, 'right'),
    ],
    margin: [0, 10, 0, 14] as [number, number, number, number],
  }
}

function partyColumn(
  label: string,
  party: PartialInvoice['from'] | PartialInvoice['client'] | undefined,
  align: 'left' | 'right'
): Column {
  const lines: Content[] = [
    { text: label, fontSize: 8, bold: true, color: COLORS.light, alignment: align, characterSpacing: 1.5 },
  ]

  if (!party?.name) {
    lines.push({
      text: '\u2014',
      fontSize: 14,
      bold: true,
      color: COLORS.placeholder,
      alignment: align,
      margin: [0, 4, 0, 0],
    })
    return { stack: lines, width: '*' } as Column
  }

  // Name
  lines.push({
    text: party.name,
    fontSize: 14,
    bold: true,
    color: COLORS.black,
    alignment: align,
    margin: [0, 4, 0, 4],
  })

  // Contact details: email, phone, taxId
  if (party.email) {
    lines.push({ text: String(party.email), fontSize: 9, color: COLORS.text, alignment: align } as Content)
  }
  if (party.phone) {
    lines.push({ text: String(party.phone), fontSize: 9, color: COLORS.text, alignment: align } as Content)
  }
  if (party.taxId) {
    lines.push({ text: String(party.taxId), fontSize: 9, color: COLORS.text, alignment: align } as Content)
  }

  // Physical address
  if (party.physicalAddress) {
    lines.push({
      text: String(party.physicalAddress),
      fontSize: 9,
      color: COLORS.muted,
      alignment: align,
      lineHeight: 1.5,
      margin: [0, 3, 0, 0],
    } as Content)
  }

  // Client wallet — full address for financial records
  if (label === 'BILL TO' && party.walletAddress) {
    lines.push({
      text: String(party.walletAddress),
      fontSize: 7,
      color: COLORS.zinc600,
      alignment: align,
      characterSpacing: 0.2,
      margin: [0, 4, 0, 0],
    } as Content)
  }

  return { stack: lines, width: '*' } as Column
}

// ── Line Items (matches LineItemsTable.tsx) ──────────────────

function buildLineItems(
  items: PartialInvoice['items'],
  decimals: number
): Content {
  const safeItems = (items ?? []) as Array<{ description?: string; quantity?: number; rate?: string }>

  // UPPERCASE headers matching web text-xs font-bold tracking-widest uppercase
  const headerRow = [
    { text: '#', fontSize: 8, bold: true, color: COLORS.black, alignment: 'center' as const, characterSpacing: 1.2 },
    { text: 'DESCRIPTION', fontSize: 8, bold: true, color: COLORS.black, characterSpacing: 1.2 },
    { text: 'QTY', fontSize: 8, bold: true, color: COLORS.black, alignment: 'center' as const, characterSpacing: 1.2 },
    { text: 'RATE (PER UNIT)', fontSize: 8, bold: true, color: COLORS.black, alignment: 'right' as const, characterSpacing: 1.2 },
    { text: 'AMOUNT', fontSize: 8, bold: true, color: COLORS.black, alignment: 'right' as const, characterSpacing: 1.2 },
  ]

  const dataRows: Content[][] = safeItems.map((item, i) => {
    const qty = item.quantity ?? 0
    const rate = item.rate ?? '0'
    const lineTotal = computeLineTotal(qty, rate, decimals)
    // Format quantity with thousand separators matching web toLocaleString
    const formattedQty = qty.toLocaleString('en-US', { maximumFractionDigits: 6, useGrouping: true })
    return [
      { text: `${i + 1}`, alignment: 'center' as const, color: COLORS.zinc600 },
      { text: item.description ?? '', color: COLORS.black },
      { text: formattedQty, alignment: 'center' as const, color: COLORS.textMd },
      { text: formatAmount(rate, decimals), alignment: 'right' as const, color: COLORS.textMd },
      { text: formatAmount(lineTotal, decimals), alignment: 'right' as const, bold: true, color: COLORS.black },
    ]
  })

  if (dataRows.length === 0) {
    dataRows.push([
      { text: 'No line items', colSpan: 5, alignment: 'center' as const, color: COLORS.light, italics: true, fontSize: 9 } as Content,
      { text: '' } as Content,
      { text: '' } as Content,
      { text: '' } as Content,
      { text: '' } as Content,
    ])
  }

  return {
    table: {
      headerRows: 1,
      widths: [24, '*', 50, 95, 95],
      body: [headerRow, ...dataRows],
    },
    layout: {
      // Thick after header (matching border-b-2 border-zinc-700), thin between rows, none at edges
      hLineWidth: (i: number, node: { table: { body: unknown[][] } }) =>
        i === 1 ? 1.5 : (i > 1 && i < node.table.body.length) ? 0.3 : 0,
      vLineWidth: () => 0,
      hLineColor: (i: number) => i === 1 ? COLORS.borderThick : COLORS.borderLight,
      paddingTop: () => 8,
      paddingBottom: () => 8,
      // Zebra striping matching web even:bg-zinc-50/50
      fillColor: (rowIndex: number) => rowIndex > 0 && rowIndex % 2 === 0 ? COLORS.bgLight : null,
    },
  }
}

// ── Bottom Section: Payment Info + Totals (matches PaperTotals.tsx) ──

function buildBottomSection(
  totals: FormattedTotals,
  currency: string,
  data: PartialInvoice,
  networkName: string,
  options: PdfExportOptions
): ContentColumns {
  return {
    columns: [
      buildPaymentInfoCard(data, networkName, currency, options),
      buildTotalsColumn(totals, currency, data.tax, data.discount),
    ],
    margin: [0, 8, 0, 0] as [number, number, number, number],
  }
}

/** Payment Info card matching PaymentInfo.tsx bordered card */
function buildPaymentInfoCard(
  data: PartialInvoice,
  networkName: string,
  currency: string,
  options: PdfExportOptions
): Column {
  const walletAddress = data.from?.walletAddress ? String(data.from.walletAddress) : ''
  const cardContent: Content[] = []

  // Network row
  if (networkName) {
    cardContent.push({
      columns: [
        { text: 'NETWORK', fontSize: 7.5, bold: true, color: COLORS.muted, width: 65, characterSpacing: 1 },
        { text: networkName, fontSize: 9, bold: true, color: COLORS.text },
      ],
      margin: [0, 0, 0, 4] as [number, number, number, number],
    })
  }

  // Token row (with full contract address for financial records)
  if (currency) {
    const tokenContent: Content[] = [
      { text: currency, fontSize: 9, bold: true, color: COLORS.text },
    ]
    if (data.tokenAddress) {
      tokenContent.push({
        text: String(data.tokenAddress),
        fontSize: 6.5,
        color: COLORS.zinc600,
        characterSpacing: 0.2,
        margin: [0, 2, 0, 0],
      })
    }
    cardContent.push({
      columns: [
        { text: 'TOKEN', fontSize: 7.5, bold: true, color: COLORS.muted, width: 65, characterSpacing: 1 },
        { stack: tokenContent },
      ],
      margin: [0, 0, 0, 6] as [number, number, number, number],
    })
  }

  // Recipient wallet — full address in bordered box for financial records
  if (walletAddress) {
    cardContent.push(
      { text: 'RECIPIENT WALLET', fontSize: 7.5, bold: true, color: COLORS.muted, characterSpacing: 1, margin: [0, 0, 0, 3] } as Content,
      {
        table: {
          widths: ['*'],
          body: [[{
            text: walletAddress,
            fontSize: 6.5,
            color: COLORS.black,
            characterSpacing: 0.2,
            margin: [4, 4, 4, 4],
          }]],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          hLineColor: () => COLORS.borderLight,
          vLineColor: () => COLORS.borderLight,
        },
        margin: [0, 0, 0, 6],
      } as Content
    )
  }

  // QR Code — full card width for long VoidPay URLs (~1000+ chars)
  if (options.invoiceUrl) {
    cardContent.push({
      stack: [
        { qr: options.invoiceUrl, fit: 120, alignment: 'center' as const, margin: [0, 4, 0, 2] },
        { text: 'SCAN TO PAY', fontSize: 6, bold: true, color: COLORS.light, alignment: 'center' as const, characterSpacing: 0.8 },
      ],
    })
  }

  // Transaction hash — full hash in colored box for financial records
  if (options.txHash) {
    cardContent.push(
      { text: 'TRANSACTION', fontSize: 7.5, bold: true, color: COLORS.muted, characterSpacing: 1, margin: [0, 6, 0, 3] } as Content,
      {
        table: {
          widths: ['*'],
          body: [[{
            text: options.txHash,
            fontSize: 6.5,
            color: COLORS.txText,
            characterSpacing: 0.2,
            margin: [4, 4, 4, 4],
          }]],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          hLineColor: () => COLORS.txBorder,
          vLineColor: () => COLORS.txBorder,
          fillColor: () => COLORS.txBg,
        },
      } as Content
    )
  }

  // Fallback for empty card
  if (cardContent.length === 0) {
    cardContent.push({ text: 'No payment details', fontSize: 8, color: COLORS.light, italics: true } as Content)
  }

  return {
    table: {
      widths: ['*'],
      body: [
        // Card header
        [{
          text: 'PAYMENT INFO',
          fontSize: 7.5,
          bold: true,
          color: COLORS.muted,
          characterSpacing: 1.2,
          fillColor: COLORS.bgMuted,
          margin: [10, 5, 10, 5],
        }],
        // Card body
        [{
          stack: cardContent,
          fillColor: COLORS.bgLight,
          margin: [10, 10, 10, 10],
        }],
      ],
    },
    layout: {
      hLineWidth: (i: number) => i === 1 ? 0 : 0.5,
      vLineWidth: () => 0.5,
      hLineColor: () => COLORS.borderLight,
      vLineColor: () => COLORS.borderLight,
    },
    width: 240,
  } as Column
}

/** Totals column matching TotalsSection.tsx with violet total */
function buildTotalsColumn(
  totals: FormattedTotals,
  currency: string,
  tax: string | undefined,
  discount: string | undefined
): Column {
  const currencyLabel = currency || 'TOKEN'
  const rows: Content[] = []

  // Subtotal
  rows.push(totalsRow('Subtotal', totals.subtotal, currencyLabel))

  // Tax (red)
  if (tax && tax !== '0') {
    rows.push(totalsRow(`Tax (${tax}%)`, `+${totals.taxAmount}`, currencyLabel, COLORS.taxRed))
  }

  // Discount (green)
  if (discount && discount !== '0') {
    rows.push(totalsRow(`Discount (${discount}%)`, `-${totals.discountAmount}`, currencyLabel, COLORS.discountGreen))
  }

  // Divider matching web border-t border-zinc-200
  rows.push({
    canvas: [{ type: 'line', x1: 0, y1: 0, x2: 220, y2: 0, lineWidth: 0.5, lineColor: COLORS.borderLight }],
    margin: [0, 6, 0, 6],
  })

  // Total — large violet matching web text-2xl font-black text-violet-600
  rows.push({
    columns: [
      { text: 'Total', fontSize: 16, bold: true, color: COLORS.black, width: 'auto' },
      {
        text: [
          { text: totals.total, fontSize: 22, bold: true, color: COLORS.brand },
          { text: ` ${currencyLabel}`, fontSize: 10, bold: true, color: COLORS.muted },
        ],
        alignment: 'right' as const,
      },
    ],
  })

  // Magic Dust
  if (totals.magicDust) {
    rows.push({
      text: [
        { text: 'Magic Dust: ', fontSize: 8, color: COLORS.muted },
        { text: `+${totals.magicDust} ${currencyLabel}`, fontSize: 8, color: COLORS.muted },
      ],
      alignment: 'right' as const,
      margin: [0, 2, 0, 0],
    })
  }

  return { stack: rows, width: '*', margin: [16, 0, 0, 0] } as Column
}

function totalsRow(
  label: string,
  amount: string,
  currency: string,
  amountColor?: string
): Content {
  return {
    columns: [
      { text: label, fontSize: 10, color: COLORS.muted, width: '*' },
      { text: amount, fontSize: 10, color: amountColor ?? COLORS.text, alignment: 'right' as const, width: 'auto' },
      { text: ` ${currency}`, fontSize: 10, color: COLORS.muted, width: 'auto' },
    ],
    margin: [0, 2, 0, 2] as [number, number, number, number],
  }
}

// ── Content Footer (matches PaperFooter.tsx) ────────────────

function buildContentFooter(notes: string | undefined): Content {
  const noteText = notes
    ?? 'Payment is due by the date shown above. Please send the exact amount to the wallet address provided.'

  return {
    stack: [
      { text: 'Thank you for your business!', fontSize: 10, bold: true, color: COLORS.black },
      { text: noteText, fontSize: 9, color: COLORS.muted, lineHeight: 1.5, margin: [0, 3, 0, 0] },
    ],
  }
}

// ── Calculations ────────────────────────────────────────────

interface FormattedTotals {
  subtotal: string
  taxAmount: string
  discountAmount: string
  total: string
  magicDust: string | null
}

function computeLineTotal(qty: number, rate: string, decimals: number): string {
  try {
    const scale = 10n ** BigInt(decimals)
    const qtyScaled = BigInt(Math.round(qty * Number(scale)))
    return ((qtyScaled * BigInt(rate || '0')) / scale).toString()
  } catch {
    return '0'
  }
}

function computeTotals(data: PartialInvoice, decimals: number): FormattedTotals {
  const items = (data.items ?? []) as Array<{ quantity?: number; rate?: string }>
  const mappedItems = items.map((item) => ({ quantity: item.quantity ?? 0, rate: item.rate ?? '0' }))
  const result = calculateTotalsBigInt(mappedItems, { tax: data.tax, discount: data.discount, decimals })

  const displayTotal = data.total
    ? (data.magicDust ? (BigInt(data.total) - BigInt(data.magicDust)).toString() : data.total)
    : result.total

  return {
    subtotal: formatAmount(result.subtotal, decimals),
    taxAmount: formatAmount(result.taxAmount, decimals),
    discountAmount: formatAmount(result.discountAmount, decimals),
    total: formatAmount(displayTotal, decimals),
    magicDust: data.magicDust ? formatAmount(data.magicDust, decimals, { displayDecimals: 6 }) : null,
  }
}
