import type { TDocumentDefinitions, Content, ContentColumns, Column } from 'pdfmake/interfaces'
import { formatAmount, calculateTotalsBigInt } from '@/shared/lib/amount-utils'
import { formatDateUTC } from '@/shared/lib/date-time'
import { getNetworkName, getExplorerUrl } from '@/entities/network'
import { APP_URLS } from '@/shared/config'

import type { PartialInvoice } from '@/shared/lib/invoice-types'
import type { PdfExportOptions } from '../model/types'

// ── Colors (matching web InvoicePaper zinc/violet palette) ──

const COLORS = {
  black: '#18181b',       // zinc-900
  text: '#27272a',        // zinc-800
  textMd: '#3f3f46',      // zinc-700 (rate, qty values)
  zinc600: '#52525b',     // zinc-600 (row index)
  muted: '#71717a',       // zinc-500
  light: '#a1a1aa',       // zinc-400
  placeholder: '#d4d4d8', // zinc-300
  borderThick: '#3f3f46', // zinc-700 (header / table thick borders)
  borderLight: '#e4e4e7', // zinc-200 (row borders, card borders)
  borderDashed: '#d4d4d8', // zinc-300 (footer dashed)
  brand: '#7c3aed',       // violet-600 (total amount)
  bgLight: '#fafafa',     // zinc-50 (card body, zebra rows)
  bgMuted: '#f4f4f5',     // zinc-100 (card header)
  taxRed: '#991b1b',      // red-800
  discountGreen: '#059669', // emerald-600
  txBg: '#ecfdf5',        // emerald-50
  txBorder: '#a7f3d0',    // emerald-200
  txText: '#065f46',      // emerald-800
} as const

/** Content width for A4 with 50pt margins: 595 - 50 - 50 */
const CONTENT_WIDTH = 495

// ── SVG Icons (matching web Lucide icons in PartyInfo.tsx) ──

const ICON_SIZE = 9

function makeSvg(paths: string): string {
  return `<svg viewBox="0 0 24 24" width="${ICON_SIZE}" height="${ICON_SIZE}" fill="none" stroke="${COLORS.light}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`
}

const ICONS = {
  mail: makeSvg('<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>'),
  phone: makeSvg('<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>'),
  hash: makeSvg('<line x1="4" x2="20" y1="9" y2="9"/><line x1="4" x2="20" y1="15" y2="15"/><line x1="10" x2="8" y1="3" y2="21"/><line x1="16" x2="14" y1="3" y2="21"/>'),
  mapPin: makeSvg('<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>'),
  wallet: makeSvg('<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>'),
  globe: makeSvg('<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>'),
  coin: makeSvg('<circle cx="12" cy="12" r="10"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 18V6"/>'),
  fingerprint: makeSvg('<path d="M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4"/><path d="M14 13.12c0 2.38 0 6.38-1 8.88"/><path d="M17.29 21.02c.12-.6.43-2.3.5-3.02"/><path d="M2 12a10 10 0 0 1 18-6"/><path d="M2 16h.01"/><path d="M21.8 16c.2-2 .131-5.354 0-6"/><path d="M5 19.5C5.5 18 6 15 6 12a6 6 0 0 1 .34-2"/><path d="M8.65 22c.21-.66.45-1.32.57-2"/><path d="M9 6.8a6 6 0 0 1 9 5.2v2"/>'),
} as const

// ── Public API ──────────────────────────────────────────────

/**
 * Build pdfmake document definition from invoice data.
 * Layout closely matches the web InvoicePaper component.
 */
export function buildDocument(
  data: PartialInvoice,
  options: PdfExportOptions
): TDocumentDefinitions {
  const decimals = data.decimals ?? 6
  const currency = data.currency ?? ''
  const invoiceId = data.invoiceId ?? 'DRAFT'
  const networkName = data.networkId ? getNetworkName(data.networkId) : ''
  const totals = computeTotals(data, decimals)

  return {
    pageSize: 'A4',
    pageOrientation: 'portrait',
    pageMargins: [50, 50, 50, 60] as [number, number, number, number],
    watermark: options.status && options.status !== 'pending'
      ? {
          text: options.status === 'paid' && options.paidAt
            ? `${options.status.toUpperCase()}\n${formatDateUTC(options.paidAt)}`
            : options.status.toUpperCase(),
          opacity: 0.10, bold: true, fontSize: 72, color: COLORS.muted,
        }
      : undefined,
    content: [
      buildHeader(invoiceId, data, options),
      thickRule(),
      buildParties(data),
      buildLineItems(data.items, decimals),
      thickRule(),
      buildBottomSection(totals, currency, data, networkName, options),
      dashedRule(),
      buildContentFooter(data.notes),
    ],
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: COLORS.text,
      lineHeight: 1.3,
    },
    footer: {
      text: [
        { text: 'Generated by VoidPay \u00B7 ', color: COLORS.muted },
        { text: 'voidpay.xyz', color: COLORS.muted, link: APP_URLS.base },
      ],
      alignment: 'center',
      fontSize: 7.5,
      margin: [0, 15, 0, 0],
    },
  }
}

/**
 * Generate PDF filename from invoice data.
 * Format: voidpay-{invoiceId}-{total}-{currency}.pdf
 */
export function buildFilename(data: PartialInvoice): string {
  const id = data.invoiceId
  const currency = data.currency
  const decimals = data.decimals ?? 6

  if (!id && !data.total) return 'voidpay-invoice.pdf'

  const rawTotal = data.total ? getDisplayTotal(data.total, data.magicDust) : undefined
  const totalStr = rawTotal
    ? formatAmount(rawTotal, decimals, { useGrouping: false })
    : undefined

  const parts = ['voidpay']
  if (id) parts.push(id)
  if (totalStr) parts.push(totalStr)
  if (currency) parts.push(currency)

  return parts.length > 1 ? `${parts.join('-')}.pdf` : 'voidpay-invoice.pdf'
}

// ── Separators ──────────────────────────────────────────────

/** Thick dark rule matching web border-b-2 border-zinc-700 */
function thickRule(): Content {
  return {
    canvas: [{ type: 'line', x1: 0, y1: 0, x2: CONTENT_WIDTH, y2: 0, lineWidth: 1.5, lineColor: COLORS.borderThick }],
    margin: [0, 12, 0, 12],
  }
}

/** Dashed rule matching web border-t border-dashed border-zinc-300 */
function dashedRule(): Content {
  return {
    canvas: [{
      type: 'line', x1: 0, y1: 0, x2: CONTENT_WIDTH, y2: 0,
      lineWidth: 0.5, lineColor: COLORS.borderDashed,
      dash: { length: 4, space: 3 },
    }],
    margin: [0, 10, 0, 10],
  }
}

// ── Header (matches PaperHeader.tsx) ────────────────────────

function buildHeader(
  invoiceId: string,
  data: PartialInvoice,
  options: PdfExportOptions
): ContentColumns {
  const issuedDate = data.issuedAt ? formatDateUTC(data.issuedAt) : '\u2014'
  const dueDate = data.dueAt ? formatDateUTC(data.dueAt) : '\u2014'
  const isDraft = invoiceId === 'DRAFT'

  // Left: "INVOICE #ID" matching web text-4xl font-black uppercase
  const titleLine: Content = {
    text: [
      { text: 'INVOICE ', fontSize: 26, bold: true, color: COLORS.light },
      isDraft
        ? { text: 'Draft', fontSize: 26, italics: true, color: COLORS.placeholder }
        : {
            text: `#${invoiceId}`, fontSize: 26, bold: true,
            color: options.invoiceUrl ? COLORS.brand : COLORS.black,
            link: options.invoiceUrl,
          },
    ],
  }

  // Right: stacked date rows matching web vertical layout
  const metaRows: Content[] = [
    metaRow('ISSUED', issuedDate),
    metaRow('DUE', dueDate, [0, 4, 0, 0]),
  ]

  if (options.status) {
    metaRows.push(metaRow('STATUS', options.status.toUpperCase(), [0, 4, 0, 0], COLORS.brand))
  }

  return {
    columns: [
      { stack: [titleLine], width: '*' } as Column,
      { stack: metaRows, width: 170, alignment: 'right' } as Column,
    ],
  }
}

function metaRow(
  label: string,
  value: string,
  margin?: [number, number, number, number],
  valueColor?: string
): Content {
  return {
    columns: [
      { text: label, fontSize: 8, bold: true, color: COLORS.light, width: 48, characterSpacing: 1.2 },
      { text: value, fontSize: 10, bold: !!valueColor, color: valueColor ?? COLORS.text, alignment: 'right' as const },
    ],
    ...(margin ? { margin } : {}),
  }
}

// ── Parties (matches PartyInfo.tsx) ─────────────────────────

function buildParties(data: PartialInvoice): ContentColumns {
  return {
    columns: [
      partyColumn('FROM', data.from, 'left'),
      partyColumn('BILL TO', data.client, 'right'),
    ],
    margin: [0, 10, 0, 14] as [number, number, number, number],
  }
}

/** Party detail row with inline SVG icon (matching web PartyInfo Lucide icons) */
function detailRow(
  icon: string,
  text: string,
  align: 'left' | 'right',
  opts?: { fontSize?: number; color?: string; lineHeight?: number; margin?: [number, number, number, number]; link?: string }
): Content {
  const fontSize = opts?.fontSize ?? 9
  const iconTop = fontSize >= 8 ? 1 : 0
  const iconCol = { svg: icon, width: ICON_SIZE, margin: [0, iconTop, 0, 0] } as Column
  const textCol = {
    text,
    fontSize,
    color: opts?.link ? COLORS.text : (opts?.color ?? COLORS.text),
    alignment: align,
    lineHeight: opts?.lineHeight,
    characterSpacing: opts?.fontSize && opts.fontSize < 8 ? 0.2 : undefined,
    link: opts?.link,
    width: '*',
  } as Column

  return {
    columns: align === 'right' ? [textCol, iconCol] : [iconCol, textCol],
    columnGap: 5,
    margin: opts?.margin ?? [0, 3, 0, 0],
  }
}

function partyColumn(
  label: string,
  party: PartialInvoice['from'] | PartialInvoice['client'] | undefined,
  align: 'left' | 'right'
): Column {
  const lines: Content[] = [
    { text: label, fontSize: 8, bold: true, color: COLORS.light, alignment: align, characterSpacing: 1.5 },
  ]

  if (!party?.name) {
    lines.push({
      text: '\u2014',
      fontSize: 14,
      bold: true,
      color: COLORS.placeholder,
      alignment: align,
      margin: [0, 4, 0, 0],
    })
    return { stack: lines, width: '*' } as Column
  }

  // Name — matching web text-lg font-bold mb-3
  lines.push({
    text: party.name,
    fontSize: 14,
    bold: true,
    color: COLORS.black,
    alignment: align,
    margin: [0, 4, 0, 6],
  })

  // Contact details with icons (matching web space-y-2: MailIcon, PhoneIcon, HashIcon)
  if (party.email) {
    lines.push(detailRow(ICONS.mail, party.email, align, { link: `mailto:${party.email}` }))
  }
  if (party.phone) {
    lines.push(detailRow(ICONS.phone, party.phone, align, { link: `tel:${party.phone}` }))
  }
  if (party.taxId) {
    lines.push(detailRow(ICONS.hash, party.taxId, align))
  }

  // Extra top spacing (matching web mt-3 + MapPinIcon)
  if (party.physicalAddress) {
    lines.push(detailRow(ICONS.mapPin, party.physicalAddress, align, {
      color: COLORS.muted,
      lineHeight: 1.5,
      margin: [0, 6, 0, 0],
    }))
  }

  // Matching web mt-3 + WalletIcon
  if (label === 'BILL TO' && party.walletAddress) {
    lines.push(detailRow(ICONS.wallet, party.walletAddress, align, {
      fontSize: 7,
      color: COLORS.zinc600,
      margin: [0, 6, 0, 0],
    }))
  }

  return { stack: lines, width: '*' } as Column
}

// ── Line Items (matches LineItemsTable.tsx) ──────────────────

function buildLineItems(
  items: PartialInvoice['items'],
  decimals: number
): Content {
  const safeItems = (items ?? []) as Array<{ description?: string; quantity?: number; rate?: string }>

  // UPPERCASE headers matching web text-xs font-bold tracking-widest uppercase
  const headerRow = [
    { text: '#', fontSize: 8, bold: true, color: COLORS.black, alignment: 'center' as const, characterSpacing: 1.2 },
    { text: 'DESCRIPTION', fontSize: 8, bold: true, color: COLORS.black, characterSpacing: 1.2 },
    { text: 'QTY', fontSize: 8, bold: true, color: COLORS.black, alignment: 'center' as const, characterSpacing: 1.2 },
    { text: 'RATE (PER UNIT)', fontSize: 8, bold: true, color: COLORS.black, alignment: 'right' as const, characterSpacing: 1.2 },
    { text: 'AMOUNT', fontSize: 8, bold: true, color: COLORS.black, alignment: 'right' as const, characterSpacing: 1.2 },
  ]

  const dataRows: Content[][] = safeItems.map((item, i) => {
    const qty = item.quantity ?? 0
    const rate = item.rate ?? '0'
    const lineTotal = computeLineTotal(qty, rate, decimals)
    // Format quantity with thousand separators matching web toLocaleString
    const formattedQty = qty.toLocaleString('en-US', { maximumFractionDigits: 6, useGrouping: true })
    return [
      { text: `${i + 1}`, alignment: 'center' as const, color: COLORS.zinc600 },
      { text: item.description ?? '', color: COLORS.black },
      { text: formattedQty, alignment: 'center' as const, color: COLORS.textMd },
      { text: formatAmount(rate, decimals), alignment: 'right' as const, color: COLORS.textMd },
      { text: formatAmount(lineTotal, decimals), alignment: 'right' as const, bold: true, color: COLORS.black },
    ]
  })

  if (dataRows.length === 0) {
    dataRows.push([
      { text: 'No line items', colSpan: 5, alignment: 'center' as const, color: COLORS.light, italics: true, fontSize: 9 } as Content,
      { text: '' } as Content,
      { text: '' } as Content,
      { text: '' } as Content,
      { text: '' } as Content,
    ])
  }

  return {
    table: {
      headerRows: 1,
      widths: [24, '*', 50, 95, 95],
      body: [headerRow, ...dataRows],
    },
    layout: {
      // Thick after header (matching border-b-2 border-zinc-700), thin between rows, none at edges
      hLineWidth: (i: number, node: { table: { body: unknown[][] } }) =>
        i === 1 ? 1.5 : (i > 1 && i < node.table.body.length) ? 0.3 : 0,
      vLineWidth: () => 0,
      hLineColor: (i: number) => i === 1 ? COLORS.borderThick : COLORS.borderLight,
      paddingTop: () => 8,
      paddingBottom: () => 8,
      // Zebra striping matching web even:bg-zinc-50/50
      fillColor: (rowIndex: number) => rowIndex > 0 && rowIndex % 2 === 0 ? COLORS.bgLight : null,
    },
  }
}

// ── Bottom Section: Payment Info + Totals (matches PaperTotals.tsx) ──

function buildBottomSection(
  totals: FormattedTotals,
  currency: string,
  data: PartialInvoice,
  networkName: string,
  options: PdfExportOptions
): ContentColumns {
  return {
    columns: [
      buildPaymentInfoCard(data, networkName, currency, options),
      buildTotalsColumn(totals, currency, data.tax, data.discount),
    ],
    margin: [0, 8, 0, 0] as [number, number, number, number],
  }
}

/** Payment Info card — compact key-value list with unified icon + value pattern */
function buildPaymentInfoCard(
  data: PartialInvoice,
  networkName: string,
  currency: string,
  options: PdfExportOptions
): Column {
  const walletAddress = data.from?.walletAddress ?? ''
  const cardContent: Content[] = []

  if (networkName) {
    cardContent.push({
      columns: [
        { svg: ICONS.globe, width: ICON_SIZE, margin: [0, 1, 0, 0] } as Column,
        { text: networkName, fontSize: 9, bold: true, color: COLORS.text },
      ],
      columnGap: 5,
      margin: [0, 0, 0, 5] as [number, number, number, number],
    })
  }

  if (currency) {
    cardContent.push({
      columns: [
        { svg: ICONS.coin, width: ICON_SIZE, margin: [0, 1, 0, 0] } as Column,
        { text: currency, fontSize: 9, bold: true, color: COLORS.text },
      ],
      columnGap: 5,
      margin: [0, 0, 0, data.tokenAddress ? 2 : 5] as [number, number, number, number],
    })
    if (data.tokenAddress) {
      cardContent.push({
        text: data.tokenAddress,
        fontSize: 6.5,
        color: COLORS.zinc600,
        characterSpacing: 0.2,
        margin: [ICON_SIZE + 5, 0, 0, 5],
      } as Content)
    }
  }

  if (walletAddress && cardContent.length > 0) {
    cardContent.push({
      canvas: [{ type: 'line', x1: 0, y1: 0, x2: 200, y2: 0, lineWidth: 0.3, lineColor: COLORS.borderLight }],
      margin: [0, 2, 0, 6],
    } as Content)
  }

  if (walletAddress) {
    cardContent.push({
      columns: [
        { svg: ICONS.wallet, width: ICON_SIZE } as Column,
        { text: walletAddress, fontSize: 6.5, color: COLORS.black, characterSpacing: 0.2 },
      ],
      columnGap: 5,
      margin: [0, 0, 0, 6] as [number, number, number, number],
    })
  }

  // QR Code — only for pending invoices (paid invoices show tx hash instead)
  if (options.invoiceUrl && (!options.status || options.status === 'pending')) {
    cardContent.push({
      stack: [
        { qr: options.invoiceUrl, fit: 120, alignment: 'center' as const, margin: [0, 4, 0, 2] },
        { text: 'SCAN TO PAY', fontSize: 6, bold: true, color: COLORS.light, alignment: 'center' as const, characterSpacing: 0.8 },
      ],
    })
  }

  if (options.txHash) {
    const explorerUrl = data.networkId ? getExplorerUrl(data.networkId, options.txHash) : undefined
    cardContent.push(
      {
        columns: [
          { svg: ICONS.hash, width: ICON_SIZE, margin: [0, 1, 0, 0] } as Column,
          { text: 'Transaction', fontSize: 7.5, bold: true, color: COLORS.muted },
        ],
        columnGap: 3,
        margin: [0, 6, 0, 2],
      } as Content,
      {
        text: options.txHash,
        fontSize: 6,
        color: COLORS.txText,
        characterSpacing: 0.1,
        link: explorerUrl,
      } as Content
    )
  }

  // Fallback
  if (cardContent.length === 0) {
    cardContent.push({ text: 'No payment details', fontSize: 8, color: COLORS.light, italics: true } as Content)
  }

  return {
    table: {
      widths: ['*'],
      body: [
        [{
          text: 'PAYMENT INFO',
          fontSize: 7.5,
          bold: true,
          color: COLORS.muted,
          characterSpacing: 1.2,
          fillColor: COLORS.bgMuted,
          margin: [10, 5, 10, 5],
        }],
        [{
          stack: cardContent,
          fillColor: COLORS.bgLight,
          margin: [10, 10, 10, 10],
        }],
      ],
    },
    layout: {
      hLineWidth: (i: number) => i === 1 ? 0 : 0.5,
      vLineWidth: () => 0.5,
      hLineColor: () => COLORS.borderLight,
      vLineColor: () => COLORS.borderLight,
    },
    width: 240,
  } as Column
}

/** Totals column matching TotalsSection.tsx with violet total */
function buildTotalsColumn(
  totals: FormattedTotals,
  currency: string,
  tax: string | undefined,
  discount: string | undefined
): Column {
  const currencyLabel = currency || 'TOKEN'
  const rows: Content[] = []

  // Subtotal
  rows.push(totalsRow('Subtotal', totals.subtotal, currencyLabel))

  // Tax (red)
  if (tax && tax !== '0') {
    rows.push(totalsRow(`Tax (${tax}%)`, `+${totals.taxAmount}`, currencyLabel, COLORS.taxRed))
  }

  // Discount (green)
  if (discount && discount !== '0') {
    rows.push(totalsRow(`Discount (${discount}%)`, `-${totals.discountAmount}`, currencyLabel, COLORS.discountGreen))
  }

  // Divider matching web border-t border-zinc-200
  rows.push({
    canvas: [{ type: 'line', x1: 0, y1: 0, x2: 220, y2: 0, lineWidth: 0.5, lineColor: COLORS.borderLight }],
    margin: [0, 6, 0, 6],
  })

  // Total — large violet matching web text-2xl font-black text-violet-600
  rows.push({
    columns: [
      { text: 'Total', fontSize: 16, bold: true, color: COLORS.black, width: 'auto', margin: [0, 5, 0, 0] },
      {
        text: [
          { text: `${totals.total}  `, fontSize: 22, bold: true, color: COLORS.brand },
          { text: currencyLabel, fontSize: 11, bold: true, color: COLORS.muted },
        ],
        alignment: 'right' as const,
      },
    ],
    margin: [0, 2, 0, 0] as [number, number, number, number],
  })

  // Magic Dust (matching web MagicDustBadge with FingerprintIcon)
  if (totals.magicDust) {
    rows.push({
      columns: [
        { text: '', width: '*' } as Column,
        { svg: ICONS.fingerprint, width: ICON_SIZE, margin: [0, 1, 0, 0] } as Column,
        {
          text: [
            { text: 'Unique ID: ', fontSize: 8, color: COLORS.muted },
            { text: `${totals.magicDust} ${currencyLabel}`, fontSize: 8, color: COLORS.muted },
          ],
          width: 'auto',
        } as Column,
      ],
      columnGap: 3,
      margin: [0, 4, 0, 0],
    })
  }

  return { stack: rows, width: '*', margin: [24, 0, 0, 0] } as Column
}

function totalsRow(
  label: string,
  amount: string,
  currency: string,
  amountColor?: string
): Content {
  return {
    columns: [
      { text: label, fontSize: 10, color: COLORS.muted, width: '*' },
      { text: amount, fontSize: 10, color: amountColor ?? COLORS.text, alignment: 'right' as const, width: 'auto' },
      { text: currency, fontSize: 10, color: COLORS.muted, width: 'auto', margin: [6, 0, 0, 0] },
    ],
    margin: [0, 3, 0, 3] as [number, number, number, number],
  }
}

// ── Content Footer (matches PaperFooter.tsx) ────────────────

function buildContentFooter(notes: string | undefined): Content {
  const noteText = notes
    ?? 'Payment is due by the date shown above. Please send the exact amount to the wallet address provided.'

  return {
    columns: [
      {
        stack: [
          { text: 'Thank you for your business!', fontSize: 10, bold: true, color: COLORS.black },
          { text: noteText, fontSize: 9, color: COLORS.muted, lineHeight: 1.5, margin: [0, 3, 0, 0] },
        ],
        width: '*',
      } as Column,
      {
        stack: [
          {
            text: 'Powered by VoidPay',
            fontSize: 8,
            bold: true,
            color: COLORS.muted,
            alignment: 'right' as const,
            characterSpacing: 0.5,
            link: APP_URLS.base,
          },
          {
            text: 'Create your own crypto invoice for free.',
            fontSize: 7,
            color: COLORS.light,
            alignment: 'right' as const,
            link: `${APP_URLS.base}/create`,
            margin: [0, 2, 0, 0],
          },
        ],
        width: 'auto',
      } as Column,
    ],
    columnGap: 20,
  }
}

// ── Calculations ────────────────────────────────────────────

/** Total minus magic dust — the amount users see (not the exact payment amount) */
function getDisplayTotal(total: string, magicDust?: string): string {
  return magicDust ? (BigInt(total) - BigInt(magicDust)).toString() : total
}

interface FormattedTotals {
  subtotal: string
  taxAmount: string
  discountAmount: string
  total: string
  magicDust: string | null
}

function computeLineTotal(qty: number, rate: string, decimals: number): string {
  try {
    const scale = 10n ** BigInt(decimals)
    const qtyScaled = BigInt(Math.round(qty * Number(scale)))
    return ((qtyScaled * BigInt(rate || '0')) / scale).toString()
  } catch {
    return '0'
  }
}

function computeTotals(data: PartialInvoice, decimals: number): FormattedTotals {
  const items = (data.items ?? []) as Array<{ quantity?: number; rate?: string }>
  const mappedItems = items.map((item) => ({ quantity: item.quantity ?? 0, rate: item.rate ?? '0' }))
  const result = calculateTotalsBigInt(mappedItems, { tax: data.tax, discount: data.discount, decimals })

  const displayTotal = data.total
    ? getDisplayTotal(data.total, data.magicDust)
    : result.total

  return {
    subtotal: formatAmount(result.subtotal, decimals),
    taxAmount: formatAmount(result.taxAmount, decimals),
    discountAmount: formatAmount(result.discountAmount, decimals),
    total: formatAmount(displayTotal, decimals),
    magicDust: data.magicDust ? formatAmount(data.magicDust, decimals, { displayDecimals: 6 }) : null,
  }
}
