/**
 * Prebuild script: precompute createHash strings for landing page demo invoices.
 *
 * Runs `encodeInvoice` over RAW_DEMO_INVOICES at build time (Node/tsx),
 * then writes a static module so DemoSection never loads brotli-wasm on the client.
 *
 * Output: src/widgets/landing/constants/demo-invoices.generated.ts
 *
 * Usage (automatic via package.json prebuild):
 *   pnpm build  →  prebuild hook runs this script first
 */

import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { encodeInvoice, generateSalt, deriveMagicDust } from '../src/features/invoice-codec'
import { addMagicDust } from '../src/shared/lib/amount-utils'
import { RAW_DEMO_INVOICES } from '../src/widgets/landing/constants/demo-invoices'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = join(__dirname, '../src/widgets/landing/constants/demo-invoices.generated.ts')

async function main(): Promise<void> {
  console.log('[prebuild] Generating demo invoice hashes...')

  const entries = await Promise.all(
    RAW_DEMO_INVOICES.map(async (invoice) => {
      const salt = generateSalt()
      const dust = deriveMagicDust(salt)
      const totalWithDust = addMagicDust(invoice.data.total!, dust)
      const dataWithDust = { ...invoice.data, total: totalWithDust, magicDust: dust.toString() }
      const createHash = await encodeInvoice(dataWithDust, salt)
      return { invoiceId: invoice.invoiceId, createHash }
    }),
  )

  const lines = [
    '/**',
    ' * AUTO-GENERATED by scripts/generate-demo-hashes.ts — do not edit manually.',
    ' * Re-generated on every `pnpm build` run (prebuild hook).',
    ' */',
    '',
    'export const DEMO_CREATE_HASHES: Record<string, string> = {',
    ...entries.map(({ invoiceId, createHash }) => `  '${invoiceId}': '${createHash}',`),
    '}',
    '',
  ]

  writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf8')
  console.log(`[prebuild] Wrote ${entries.length} hashes to ${OUTPUT_PATH}`)
}

main().catch((err: unknown) => {
  console.error('[prebuild] Failed to generate demo hashes:', err)
  process.exit(1)
})
